config/routes.rb
Rails.application.routes.draw do
  root 'neighborhoods#index'

  get '/activities' => 'activities#index'

  resources :neighborhoods do
    resources :activities
  end

end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  has_many :activities
  validates :name, :uniqueness => true, :presence => true
end

#require unique name, and presence of name.

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :get_neighborhood, only: [:show, :edit, :update, :destroy]

  def get_neighborhood
    @neighborhood = Neighborhood.find(params[:id])
  end

  def index
    @neighborhoods = Neighborhood.all
  end

  def show
    @activities = @neighborhood.activities
  end

  def edit
  end

  def update
    @neighborhood.update(neighborhood_params)
    redirect_to neighborhoods_path
  end

  def new
    @neighborhood = Neighborhood.new
  end

  def create
    @neighborhood = Neighborhood.create(neighborhood_params)
    redirect_to neighborhoods_path
  end

  def destroy
    @neighborhood.destroy
    redirect_to neighborhoods_path
  end

  private

  def neighborhood_params
    params.require(:neighborhood).permit([:name, :description])
  end
end

app/helpers/neighborhoods_helper.rb
module NeighborhoodsHelper
end

app/views/neighborhoods/_form.html.erb
<div class="neighborhood_form">
  <%= form_for @neighborhood do |f| %>
    <%= f.label :name, 'Name: ' %>
    <%= f.text_field :name, :required => true %>
    <br>
    <br>
    <%= f.label :description, 'Description: ' %>
    <br>
    <%= f.text_area :description, size: "30x10" %>
    <br>
    <br>
    <%= f.submit %>
  <% end %>
</div>

app/views/neighborhoods/edit.html.erb
<div class="neighborhood_form">
  <h1>Edit Neighborhood</h1>
</div>
<%= render 'form' %>

app/views/neighborhoods/index.html.erb
<div class="neighborhood_index">
  <h1>Welcome to Seattle!</h1>
</div>
<div class="neighborhood_index">
  <h3>Neighborhoods</h3>
  <table id="neighborhood_table">
    <% @neighborhoods.each do |n| %>
    <tr>
      <td class="neighborhood_link_cell">
        <%= link_to n.name, neighborhood_path(n) %>
      </td>
      <td class="edit_button_cell">
        <%= button_to 'Edit', edit_neighborhood_path(n), method: :get %>
      </td>
      <td class="delete_button_cell">
        <%= button_to "Delete", "/neighborhoods/#{n.id}", method: "delete",  data: { confirm: "Are you sure you want to delete this neighborhood?" } %>
      </td>
    </tr>
    <% end %>
  </table>
</div>
<div class="neighborhood_index">
  <p>
    Can't find the neighborhood you're looking for? <%= link_to 'Add a new neighborhood', new_neighborhood_path %>
  </p>
</div>

app/views/neighborhoods/new.html.erb
<div class="neighborhood_form">
  <h1>Add a Neighborhood</h1>
</div>
<%= render 'form' %>

app/views/neighborhoods/show.html.erb
<div class="neighborhood_show">
  <h1><%= @neighborhood.name %></h1>
</div>
<div class="neighborhood_show">
  <h3>Description:</h3>
  <p><%= @neighborhood.description %></p>
</div>
<div class="neighborhood_show">
  <h3>Activities:</h3>
  <table id="activity_table">
    <% @activities.each do |a| %>
      <tr>
        <td>
          <%= link_to a.name, neighborhood_activity_path(@neighborhood, a) %>
        </td>
        <td>
          <%= button_to 'Edit', edit_neighborhood_activity_path(@neighborhood, a), method: :get %>
        </td>
        <td>
          <%= button_to 'Delete',
          "/neighborhoods/#{@neighborhood.id}/activities/#{a.id}", method: "delete", data: { confirm: "Are you sure you want to delete this activity?" } %>
        </td>
      </tr>
      <% end %>
    </table>
</div>
<div class="neighborhood_show">
  <p id="add_activity">
    Contribute to the list! <%= link_to "Add an activity", new_neighborhood_activity_path(@neighborhood) %>
  </p>
</div>