config/routes.rb
Rails.application.routes.draw do
  root 'neighborhoods#index'

  get '/activities' => 'activities#index'

  resources :neighborhoods do
    resources :activities
  end

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :neighborhood
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :get_categories, only: [:index, :edit, :new]
  before_action :get_subcategories, only: [:index, :edit, :new]
  before_action :get_activity, only: [:show, :edit, :update, :destroy]
  before_action :get_methods, only: [:edit, :new]

  def get_categories
    @categories = Activity.pluck(:category).uniq
  end

  def get_subcategories
    @subcategories = Activity.pluck(:subcategory).uniq
  end

  def get_activity
    @activity = Activity.find(params[:id])
  end

  def get_methods
    @method = Activity.pluck(:method).uniq
  end

  def index
    category = params["Category"]
    subcategory = params["Subcategory"]
    neighborhood_id = params[:neighborhood][:neighborhood_id] unless params[:neighborhood] == nil
    price_range = params["Price"]
    time = params["Time"]
    if params.length == 5
      filter_activities(category, subcategory, neighborhood_id, price_range, time)
    else
      @activities = Activity.all
    end
  end

  def filter_activities(category, subcategory, neighborhood_id, price_range, time)
    if category != nil && category != ''
      @activities = Activity.where(category: category)
      @filtered_by = "Category: " + category
    elsif subcategory != nil && subcategory != ''
      @activities = Activity.where(subcategory: subcategory)
      @filtered_by = "Subcategory: " + subcategory
    elsif neighborhood_id != nil && neighborhood_id != ''
      @activities = Activity.where(neighborhood_id: neighborhood_id)
      @filtered_by = "Neighborhood: " + Neighborhood.find(neighborhood_id).name
    elsif price_range != nil && price_range != ''
      @activities = Activity.where(price_range: price_range)
      @filtered_by = "Price Range: " + price_range
    elsif time != nil && time != ''
      @filtered_by = "Time: " + time.gsub("_", " ").titleize + "s"
      @activities = Activity.where(sunday_morning: true) if time == "sunday_morning"
      @activities = Activity.where(sunday_afternoon: true) if time == "sunday_afternoon"
      @activities = Activity.where(sunday_evening: true) if time == "sunday_evening"
      @activities = Activity.where(monday_morning: true) if time == "monday_morning"
      @activities = Activity.where(monday_afternoon: true) if time == "monday_afternoon"
      @activities = Activity.where(monday_evening: true) if time == "monday_evening"
      @activities = Activity.where(tuesday_morning: true) if time == "tuesday_morning"
      @activities = Activity.where(tuesday_afternoon: true) if time == "tuesday_afternoon"
      @activities = Activity.where(tuesday_evening: true) if time == "tuesday_evening"
      @activities = Activity.where(wednesday_morning: true) if time == "wednesday_morning"
      @activities = Activity.where(wednesday_afternoon: true) if time == "wednesday_afternoon"
      @activities = Activity.where(wednesday_evening: true) if time == "wednesday_evening"
      @activities = Activity.where(thursday_morning: true) if time == "thursday_morning"
      @activities = Activity.where(thursday_afternoon: true) if time == "thursday_afternoon"
      @activities = Activity.where(thursday_evening: true) if time == "thursday_evening"
      @activities = Activity.where(friday_morning: true) if time == "friday_morning"
      @activities = Activity.where(friday_afternoon: true) if time == "friday_afternoon"
      @activities = Activity.where(friday_evening: true) if time == "friday_evening"
      @activities = Activity.where(saturday_morning: true) if time == "saturday_morning"
      @activities = Activity.where(saturday_afternoon: true) if time == "saturday_afternoon"
      @activities = Activity.where(saturday_evening: true) if time == "saturday_evening"
    else
      @activities = Activity.all
    end
  end

  def show
  end

  def edit
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
  end

  def update
    @activity.update(activity_params)
    redirect_to @activity.neighborhood
  end

  def new
    @activity = Activity.new
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
  end

  def create
    activity = Activity.create(activity_params) do |a|
      a.neighborhood = Neighborhood.find(params[:neighborhood_id])
    end
    redirect_to activity.neighborhood
  end

  def destroy
    @activity.destroy
    redirect_to @activity.neighborhood
  end

  private

  def activity_params
    params.require(:activity).permit([:name, :category, :subcategory, :description, :sunday_morning, :sunday_afternoon, :sunday_evening, :monday_morning, :monday_afternoon, :monday_evening, :tuesday_morning, :tuesday_afternoon, :tuesday_evening, :wednesday_morning, :wednesday_afternoon, :wednesday_evening, :thursday_morning, :thursday_afternoon, :thursday_evening, :friday_morning, :friday_afternoon, :friday_evening, :saturday_morning, :saturday_afternoon, :saturday_evening, :website, :price_range, :minutes_from_ada, :method, :address, :city, :state, :country, :zip])
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
  def times_when(activity)
    times_when = []
    times_when.push("Monday Mornings")if activity.monday_morning
    times_when.push("Monday Afternoons") if activity.monday_afternoon
    times_when.push("Monday Evenings") if activity.monday_evening
    times_when.push("Tuesday Mornings") if activity.tuesday_morning
    times_when.push("Tuesday Afternoons") if activity.tuesday_afternoon
    times_when.push("Tuesday Evenings") if activity.tuesday_evening
    times_when.push("Wednesday Mornings") if activity.wednesday_morning
    times_when.push("Wednesday Afternoons") if activity.wednesday_afternoon
    times_when.push("Wednesday Evenings") if activity.wednesday_evening
    times_when.push("Thursday Mornings") if activity.thursday_morning
    times_when.push("Thursday Afternoons") if activity.thursday_afternoon
    times_when.push("Thursday Evenings") if activity.thursday_evening
    times_when.push("Friday Mornings") if activity.friday_morning
    times_when.push("Friday Afternoons") if activity.friday_afternoon
    times_when.push("Friday Evenings") if activity.friday_evening
    times_when.push("Saturday Mornings") if activity.saturday_morning
    times_when.push("Saturday Afternoons") if activity.saturday_afternoon
    times_when.push("Saturday Evenings") if activity.saturday_evening
    times_when.push("Sunday Mornings") if activity.sunday_morning
    times_when.push("Sunday Afternoons") if activity.sunday_afternoon
    times_when.push("Sunday Afternoons") if activity.sunday_evening
    times_when
  end

  def us_states
    [
      ['AK', 'AK'],
      ['AL', 'AL'],
      ['AR', 'AR'],
      ['AZ', 'AZ'],
      ['CA', 'CA'],
      ['CO', 'CO'],
      ['CT', 'CT'],
      ['DC', 'DC'],
      ['DE', 'DE'],
      ['FL', 'FL'],
      ['GA', 'GA'],
      ['HI', 'HI'],
      ['IA', 'IA'],
      ['ID', 'ID'],
      ['IL', 'IL'],
      ['IN', 'IN'],
      ['KS', 'KS'],
      ['KY', 'KY'],
      ['LA', 'LA'],
      ['MA', 'MA'],
      ['MD', 'MD'],
      ['ME', 'ME'],
      ['MI', 'MI'],
      ['MN', 'MN'],
      ['MO', 'MO'],
      ['MS', 'MS'],
      ['MT', 'MT'],
      ['NC', 'NC'],
      ['ND', 'ND'],
      ['NE', 'NE'],
      ['NH', 'NH'],
      ['NJ', 'NJ'],
      ['NM', 'NM'],
      ['NV', 'NV'],
      ['NY', 'NY'],
      ['OH', 'OH'],
      ['OK', 'OK'],
      ['OR', 'OR'],
      ['PA', 'PA'],
      ['RI', 'RI'],
      ['SC', 'SC'],
      ['SD', 'SD'],
      ['TN', 'TN'],
      ['TX', 'TX'],
      ['UT', 'UT'],
      ['VA', 'VA'],
      ['VT', 'VT'],
      ['WA', 'WA'],
      ['WI', 'WI'],
      ['WV', 'WV'],
      ['WY', 'WY']
    ]
  end
end

app/views/activities/_form.html.erb
<div class="activity_form">
  <%= form_for [@neighborhood, @activity] do |f| %>
    <%= f.label :name, 'Name: ' %>
    <%= f.text_field :name, :required => true %>
    <br>
    <br>
    <%= f.label :category, 'Category: ' %>
    <%= f.select :category, @categories, prompt: "Select a category" %>
    <br>
    <br>
    <%= f.label :subcategory, 'Subcategory: ' %>
    <%= f.select :subcategory, @subcategories, prompt: "Select a subcategory" %>
    <br>
    <br>
    <%= f.label :description, 'Description: ' %>
    <br>
    <%= f.text_area :description, size: "50x5" %>
    <br>
    <br>
    When:
    <br>
    <table id="when_table">
      <tr>
        <td>
          <strong>Monday:</strong>
        </td>
        <td>
          <%= f.check_box :monday_morning %>
          <%= f.label :monday_morning, "Mornings " %>
        </td>
        <td>
          <%= f.check_box :monday_afternoon %>
          <%= f.label :monday_afternoon, "Afternoons " %>
        </td>
        <td>
          <%= f.check_box :monday_evening %>
          <%= f.label :monday_evening, "Evenings " %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Tuesday:</strong>
        </td>
        <td>
          <%= f.check_box :tuesday_morning %>
          <%= f.label :tuesday_morning, "Mornings " %>
        </td>
        <td>
          <%= f.check_box :tuesday_afternoon %>
          <%= f.label :tuesday_afternoon, "Afternoons " %>
        </td>
        <td>
          <%= f.check_box :tuesday_evening %>
          <%= f.label :tuesday_evening, "Evenings " %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Wednesday:</strong>
        </td>
        <td>
          <%= f.check_box :wednesday_morning %>
          <%= f.label :wednesday_morning, "Mornings " %>
        </td>
        <td>
          <%= f.check_box :wednesday_afternoon %>
          <%= f.label :wednesday_afternoon, "Afternoons " %>
        </td>
        <td>
          <%= f.check_box :wednesday_evening %>
          <%= f.label :wednesday_evening, "Evenings " %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Thursday:</strong>
        </td>
        <td>
          <%= f.check_box :thursday_morning %>
          <%= f.label :thursday_morning, "Mornings " %>
        </td>
        <td>
          <%= f.check_box :thursday_afternoon %>
          <%= f.label :thursday_afternoon, "Afternoons " %>
        </td>
        <td>
          <%= f.check_box :thursday_evening %>
          <%= f.label :thursday_evening, "Evenings " %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Friday:</strong>
        </td>
        <td>
          <%= f.check_box :friday_morning %>
          <%= f.label :friday_morning, "Mornings " %>
        </td>
        <td>
          <%= f.check_box :friday_afternoon %>
          <%= f.label :friday_afternoon, "Afternoons " %>
        </td>
        <td>
          <%= f.check_box :friday_evening %>
          <%= f.label :friday_evening, "Evenings " %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Saturday:</strong>
        </td>
        <td>
          <%= f.check_box :saturday_morning %>
          <%= f.label :saturday_morning, "Mornings " %>
        </td>
        <td>
          <%= f.check_box :saturday_afternoon %>
          <%= f.label :saturday_afternoon, "Afternoons " %>
        </td>
        <td>
          <%= f.check_box :saturday_evening %>
          <%= f.label :saturday_evening, "Evenings " %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Sunday:</strong>
        </td>
        <td>
          <%= f.check_box :sunday_morning %>
          <%= f.label :sunday_morning, "Mornings " %>
        </td>
        <td>
          <%= f.check_box :sunday_afternoon %>
          <%= f.label :sunday_afternoon, "Afternoons " %>
        </td>
        <td>
          <%= f.check_box :sunday_evening %>
          <%= f.label :sunday_evening, "Evenings " %>
        </td>
      </tr>
    </table>
    <br>
    <%= f.label :website, 'Website: ' %>
    <%= f.text_field :website %>
    <br>
    <br>
    <%= f.label :price_range, 'Price Range: ' %>
    <%= f.select :price_range, ["Free", "$1 - $5", "$5 - $10", "$10 - $15", "$15 - $20", "$20+"], prompt: "Select a price range" %>
    <br>
    <br>
    <%= f.label :minutes_from_ada, 'Transit Time (from Ada): ' %>
    <br>
    <%= f.number_field :minutes_from_ada %>
    minutes by
    <%= f.select :method, @method, prompt: "Select a transit method" %>
    <br>
    <br>
    <table>
      <tr>
        <td>
          <%= f.label :address, 'Address: ' %>
        </td>
        <td>
          <%= f.text_field :address %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label :city, 'City: ' %>
        </td>
        <td>
          <%= f.text_field :city, :value => "Seattle" %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label :state, 'State: ' %>
        </td>
        <td>
          <%= f.select :state, us_states, :selected => 'WA' %>
        </td>
      </tr>
      <tr>
        <td>
          <%= f.label :zip, 'Zip Code: ' %>
        </td>
        <td>
          <%= f.text_field :zip %>
        </td>
      </tr>
    </table>
    <br>
    <%= f.submit %>
  <% end %>
</div>

app/views/activities/edit.html.erb
<div class="activity_form">
  <p><%= link_to "Click Here", neighborhood_path(@neighborhood.id) %> to return to <%= @neighborhood.name %>.</p>
</div>
<div class="activity_form">
  <h1>Edit Activity</h1>
</div>
<%= render 'form' %>

app/views/activities/index.html.erb
<div class="activity_index">
  <h1>Activities</h1>
</div>
<div class="activity_index">
  <h3>List of Activities</h3>
  <% if @filtered_by != nil %>
    <p>Filtered by <%= @filtered_by %> <%= link_to 'Reset Filter', activities_path %></p>
  <% end %>
  <ul>
    <% @activities.each do |a| %>
      <li>
        <%= link_to a.name, neighborhood_activity_path(a.neighborhood_id, a.id) %>
      </li>
    <% end %>
  </ul>
</div>
<div class="activity_index">
  <h3>Filters</h3>
  <section class="filter">
    <%= form_tag '', :method => :get do %>
    <%= collection_select :neighborhood, :neighborhood_id, Neighborhood.all, :id, :name, prompt: "Select a neighborhood" %>
    <%= submit_tag 'Filter by Neighborhood' %>
    <% end %>
    <br>
    <%= form_tag '', :method => :get do %>
    <%= select_tag "Price", options_for_select(["Free", "$1 - $5", "$5 - $10", "$10 - $15", "$15 - $20", "$20+"]), prompt: "Select a price range" %>
    <%= submit_tag 'Filter by Price Range' %>
    <% end %>
    <br>
    <%= form_tag '', :method => :get do %>
    <%= select_tag "Category", options_for_select(@categories), prompt: "Select a category" %>
    <%= submit_tag 'Filter by Category' %>
    <% end %>
    <br>
    <%= form_tag '', :method => :get do %>
    <%= select_tag "Subcategory", options_for_select(@subcategories), prompt: "Select a subcategory" %>
    <%= submit_tag 'Filter by Subcategory' %>
    <% end %>
    <br>
  </section>
  <%= form_tag '', :method => :get do %>
  <table class="filter">
    <tr>
      <td>
        <strong>Monday:</strong>
      </td>
      <td>
        <%= radio_button_tag "Time", :monday_morning %>Mornings
      </td>
      <td>
        <%= radio_button_tag "Time", :monday_afternoon %>Afternoons
      </td>
      <td>
        <%= radio_button_tag "Time", :monday_evening %>Evenings
      </td>
    </tr>
    <tr>
      <td>
        <strong>Tuesday:</strong>
      </td>
      <td>
        <%= radio_button_tag "Time", :tuesday_morning %>Mornings
      </td>
      <td>
        <%= radio_button_tag "Time", :tuesday_afternoon %>Afternoons
      </td>
      <td>
        <%= radio_button_tag "Time", :tuesday_evening %>Evenings
      </td>
    </tr>
    <tr>
      <td>
        <strong>Wednesday:</strong>
      </td>
      <td>
        <%= radio_button_tag "Time", :wednesday_morning %>Mornings
      </td>
      <td>
        <%= radio_button_tag "Time", :wednesday_afternoon %>Afternoons
      </td>
      <td>
        <%= radio_button_tag "Time", :wednesday_evening %>Evenings
      </td>
    </tr>
    <tr>
      <td>
        <strong>Thursday:</strong>
      </td>
      <td>
        <%= radio_button_tag "Time", :thursday_morning %>Mornings
      </td>
      <td>
        <%= radio_button_tag "Time", :thursday_afternoon %>Afternoons
      </td>
      <td>
        <%= radio_button_tag "Time", :thursday_evening %>Evenings
      </td>
    </tr>
    <tr>
      <td>
        <strong>Friday:</strong>
      </td>
      <td>
        <%= radio_button_tag "Time", :friday_morning %>Mornings
      </td>
      <td>
        <%= radio_button_tag "Time", :friday_afternoon %>Afternoons
      </td>
      <td>
        <%= radio_button_tag "Time", :friday_evening %>Evenings
      </td>
    </tr>
    <tr>
      <td>
        <strong>Saturday:</strong>
      </td>
      <td>
        <%= radio_button_tag "Time", :saturday_morning %>Mornings
      </td>
      <td>
        <%= radio_button_tag "Time", :saturday_afternoon %>Afternoons
      </td>
      <td>
        <%= radio_button_tag "Time", :saturday_evening %>Evenings
      </td>
    </tr>
    <tr>
      <td>
        <strong>Sunday:</strong>
      </td>
      <td>
        <%= radio_button_tag "Time", :sunday_morning %>Mornings
      </td>
      <td>
        <%= radio_button_tag "Time", :sunday_afternoon %>Afternoons
      </td>
      <td>
        <%= radio_button_tag "Time", :sunday_evening %>Evenings
      </td>
    </tr>
    <tr>
      <td id="time_filter_submit">
        <%= submit_tag 'Filter by Time' %>
      </td>
    </tr>
  </table>
  <% end %>
</div>

app/views/activities/new.html.erb
<div class="activity_form">
  <p><%= link_to "Click Here", neighborhood_path(@neighborhood.id) %> to return to <%= @neighborhood.name %>.</p>
</div>
<div class="activity_form">
  <h1>Add an Activity</h1>
</div>
<%= render 'form' %>

app/views/activities/show.html.erb
<div class="activity_show">
  <h1><%= @activity.name %></h1>
</div>
<div class="activity_show">
  <table id="activity_show_table">
    <tr>
      <td>
        <strong>Neighborhood: </strong>
      </td>
      <td>
        <%= link_to @activity.neighborhood.name, neighborhood_path(@activity.neighborhood_id) %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>Category: </strong>
      </td>
      <td>
        <%= @activity.category %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>Subcategory: </strong>
      </td>
      <td>
        <%= @activity.subcategory %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>Description: </strong>
      </td>
      <td>
        <%= @activity.description %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>Website: </strong>
      </td>
      <td>
        <% if @activity.website != '' %>
          <%= link_to 'Click Here', @activity.website, :target => '_blank' %>
        <% end %>
      </td>
    </tr>
    <tr>
      <td>
        <strong>When: </strong>
      </td>
      <td>
        <% times_when(@activity).each do |time| %>
          <%= time %>
          <br>
        <% end %>
      </td>
      <tr>
        <td>
          <strong>Price Range: </strong>
        </td>
        <td>
          <%= @activity.price_range %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Transit Time: </strong>
          <br>
           (from Ada)
        </td>
        <td>
          <%= @activity.minutes_from_ada %> minutes by <%= @activity.method %>
        </td>
      </tr>
      <tr>
        <td>
          <strong>Address: </strong>
        </td>
        <td>
          <%= @activity.address %>
          <br>
          <%= @activity.city %>, <%= @activity.state %> <%= @activity.zip %>
        </td>
      </tr>
    </tr>
  </table>
</div>